### ISSUE TITLE
Replication group id's are limited to 20 chars

### ISSUE THREAD

**Issue by ghost** [skyscrapers/terraform-elasticache#3]
I was attempting to use this module in my terraform setup - and I received an error saying that the replication group id is limited to 20 characters.

Looking at the source, the id is configured as a combination of the project, the environment, and the name. If the environment is fully typed out - e.g. `development` or `production`, this 20-character limit is quickly filled up.

What if there was an additional variable added that could specify the id manually - and if the id wasn't manually specified then it would use what it currently uses (the combination of name, env, and project). The description would continue to have the full output of name-environment-project.

I'm willing to create a PR for it - just wanted to make sure it's an OK solution 😁

**Comment by iuriaranda** [comment]
Hi @rv-aburdine ,

First of all I would like to apologise for not coming back to you in time.

We're now going over all the open issues and PRs of our open-source projects and doing some cleanup of stale items. I'm going to go ahead and close this issue for now. If this is still relevant for you feel free to reopen the issue or contribute a PR 🙂 

We're making steps towards a more active community participation, so we'll do our best to respond to issues and PRs in a reasonable timeframe.
